Ansible 1
Otus-DevOps-2020-05/rust118_infra pull request #11
Opened 2020-07-13 08:25 UTC by rust118

# Выполнено ДЗ №10

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - реализовано развертывание приложения на ansible;
 - с помощью ansible-inventory создан файл inventory.json;
 - inventoty.sh при указанном параметре --list генерирует json с актуальными ip-адресами, получаемыми с помощью yc.

## Как запустить проект:
 - запустить команду terraform plan && terraform apply в директории terraform

## Как проверить работоспособность:
 - запустить команду ansible all -m ping в директории ansible

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2020-07-15 06:47 UTC, mrgreyves requested changes
Здравствуйте!) Выполните локально команду:
```
ansible-playbook --syntax-check clone.yml
```
Вывод приложите сюда.

2020-07-15 06:51 UTC, mrgreyves commented
УПД: в ansible.cfg исправьте файл инвентаря на статический который есть в репе и пушаните изменения =)

2020-07-16 06:15 UTC, mrgreyves requested changes
См. предыдущие комментарии.

2020-07-17 12:01 UTC, rust118 commented
elmar@h0:~/work/rust118_infra/ansible% ansible-playbook --syntax-check clone.yml

playbook: clone.yml

2020-07-19 09:16 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-07-19 09:16 UTC, merged